meta_product_name: "Sofia Galvão Group"
meta_title: "Sofia Galvão Group - Juntos criamos Lares Felizes!"
meta_title_backoffice: "Backoffice | Sofia Galvão Group"
meta_description:
  "Sou marketer de formação, e criadora de valor por paixão. Trabalhei durante
  anos com marcas e produtos, no propósito de melhor servir o Cliente e de lhe
  oferecer não só o que ele necessitava, mas também o que melhor respondia às
  suas aspirações. Foquei-me nas pessoas e na realização do seu potencial
  máximo, sou Master em Programação Neuro linguística e acredito na conquista da
  capacitação para a concretização de objectivos e realização de propósitos de
  vida. Dediquei-me ao sector imobiliário e exerço na compra e venda de casas a
  descoberta do activo único: da casa, do cliente, da transação, do serviço.
  Desenvolvo a consultoria imobiliária com exigência, rigor, profissionalismo e
  confiança. Tenho o “know how” do mercado e proporciono aos meus Clientes os
  melhores negócios, os que os fazem mais Felizes!"
meta_image: "banner_small.jpg" # should exist in `app/public/images/`
twitter_account: "@sofiagalvaokw" # required for Twitter Cards
